# Generated by Django 5.1.7 on 2025-04-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReFinds', '0004_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='message',
            name='reactions',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
