# Generated by Django 5.1.7 on 2025-04-19 16:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReFinds', '0004_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
