# Generated by Django 5.1.7 on 2025-04-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReFinds', '0005_ad_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
