# Generated by Django 5.1.7 on 2025-04-21 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReFinds', '0005_message_image_message_reactions_alter_message_text'),
        ('ReFinds', '0006_alter_ad_embedding'),
    ]

    operations = [
    ]
