# Generated by Django 5.1.7 on 2025-04-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReFinds', '0007_merge_20250421_0857'),
        ('ReFinds', '0007_merge_20250421_1217'),
    ]

    operations = [
    ]
