# Generated by Django 5.1.7 on 2025-04-22 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReFinds', '0008_merge_20250421_2028'),
        ('ReFinds', '0008_merge_20250422_0101'),
    ]

    operations = [
    ]
