# Generated by Django 5.2 on 2025-04-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReFinds', '0009_merge_20250422_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='title_lower',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='location',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='ad',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
