# Generated by Django 5.2 on 2025-04-26 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReFinds', '0010_ad_title_lower_alter_ad_latitude_alter_ad_location_and_more'),
        ('ReFinds', '0011_populate_title_lower'),
    ]

    operations = [
    ]
